# Generated by Django 3.2.8 on 2021-11-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retails', models.CharField(blank=True, choices=[('Retail Farmer', 'Retail Farmer'), ('Commarcial Farmer', 'Commarcial Farmer')], default='Retail Farmer', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_organition', models.CharField(max_length=300)),
                ('Full_address_location', models.TextField()),
                ('crop', models.CharField(max_length=500)),
                ('why_do_you_seeking_land', models.TextField()),
                ('how_much_you_invest', models.TextField()),
                ('passport', models.FileField(upload_to='')),
                ('national_ID_card', models.FileField(upload_to='')),
                ('farm_location', models.TextField()),
            ],
        ),
    ]
