# Generated by Django 3.2.8 on 2021-11-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='national_ID_card',
            field=models.ImageField(upload_to='media/national'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='passport',
            field=models.ImageField(upload_to='media/passport'),
        ),
    ]
