# Generated by Django 3.2.8 on 2021-11-23 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20211122_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer',
            old_name='name_organition',
            new_name='name_of_organization',
        ),
    ]
